### ISSUE TITLE
部署错误提示，求帮助!

### ISSUE THREAD

**Issue by myuanzhang** [liyupi/code-nav#51]
本人新手，部署鱼皮的导航项目时总是有下面这个错误提示，请问该怎么解决，谢谢

![部署错误](https://user-images.githubusercontent.com/68680964/161191254-d1cf352e-28a3-4829-ab49-e1ec273ee888.png)

**Comment by Cassian824** [comment]
你应该是全局安装了一个低版本的antd，把全局版本的卸掉应该就行了

**Comment by myuanzhang** [comment]
> 你应该是全局安装了一个低版本的antd，把全局版本的卸掉应该就行了

好的，谢谢
